#!/usr/bin/env bash

for porta in $(seq 2 7)
do
	for mono in $(seq 2 7)
	do
		for fagwma in $(seq 2 7)
		do
			for out in $(seq 2 7)
			do
				count=0
				for i in $(seq 1 $1)
				do
					x=`java Test3 $porta $mono $fagwma $out`
					#echo "$x"
					if [ "$x" == "Black Wins!" ]; then
						((count++))
					fi
				done
				#bwin=`expr $1 - $count`
				echo "$porta,$mono,$fagwma,$out,$count"
			done
		done
	done
done	
#echo "$count white wins in $1 games"
